### ISSUE TITLE
Code that compiles in 0.10.4 does not compile in 0.11.1

### ISSUE THREAD

**Issue by stfines-clgx** [spotify/scio#4066]
Code that compiled fine in 0.10.4 now generates a "method too large" error when the library is upgraded to 0.11.1 (and no other changes). I've raised other tickets in the past around Macros and handling large case classes against this same codebase.

for example, One of the methods that is Too large is:
`
  def execute(
      options: PipelineOptions
  )(implicit runContext: RunContext, ec: ExecutionContext): Option[ScioResult] = {
    val job = new BundlerJob(config)
    job.runBundler(options)
  }
`

**Comment by jvexiau** [comment]
duplicate of https://github.com/spotify/scio/issues/4005

**Comment by clairemcginty** [comment]
we've seen this happen as the result of too much Coder (or other macro) derivation. One thing you can try is to manually provide an implicit Coder for an SCollection type outside the enclosing method in order to reduce generated code within that method; for example:

```diff
object MyJob {
+ implicit val someClassCoder = Coder.gen[SomeClass]

   def main(args: Array[String]): Unit = {
      val data: SCollection[SomeClass] = ???
      ...
   }
}
```

Let me know whether that helps!

**Comment by kellen** [comment]
`Coder.gen` is the general solution to `MethodTooLargeError`s. 

With respect to the follow-up, we occasionally see `NoSuchMethodError` issues like this due to unclean build caches, in which case we advise:
```
rm -r $HOME/.m2/repository
rm -r $HOME/.ivy2
rm -r $HOME/.sbt

# on Linux
rm -r $HOME/.cache/coursier

# on MacOS
rm -r $HOME/Library/Caches/Coursier
```

IIRC there was also an issue with some release of magnolify that has now been fixed which could cause this.
