### ISSUE TITLE
NoSuchMethodError after upgrading to 0.9.0

### ISSUE THREAD

**Issue by pishen** [spotify/scio#2945]
I'm getting the following error when running on scio 0.9.0

```
May 05, 2020 11:38:57 AM com.google.auth.oauth2.DefaultCredentialsProvider warnAboutProblematicCredentials
WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
[run-main-3] INFO org.apache.beam.sdk.extensions.gcp.options.GcpOptions$GcpTempLocationFactory - No tempLocation specified, attempting to use default bucket: dataflow-staging-us-central1-712029094***
[error] (run-main-3) java.lang.RuntimeException: Failed to construct instance from factory method DataflowRunner#fromOptions(interface org.apache.beam.sdk.options.PipelineOptions)
[error] java.lang.RuntimeException: Failed to construct instance from factory method DataflowRunner#fromOptions(interface org.apache.beam.sdk.options.PipelineOptions)
[error] 	at org.apache.beam.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:224)
[error] 	at org.apache.beam.sdk.util.InstanceBuilder.build(InstanceBuilder.java:155)
[error] 	at org.apache.beam.sdk.PipelineRunner.fromOptions(PipelineRunner.java:55)
[error] 	at org.apache.beam.sdk.Pipeline.create(Pipeline.java:149)
[error] 	at com.spotify.scio.ScioContext.pipeline(ScioContext.scala:498)
[error] 	at com.spotify.scio.ScioContext.applyInternal(ScioContext.scala:675)
[error] 	at com.spotify.scio.ScioContext.applyInternal(ScioContext.scala:680)
[error] 	at com.spotify.scio.io.TextIO.read(TextIO.scala:48)
[error] 	at com.spotify.scio.io.TextIO.read(TextIO.scala:37)
[error] 	at com.spotify.scio.io.ScioIO$$anonfun$readWithContext$1.apply(ScioIO.scala:77)
[error] 	at com.spotify.scio.io.ScioIO$$anonfun$readWithContext$1.apply(ScioIO.scala:74)
[error] 	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:657)
[error] 	at com.spotify.scio.io.ScioIO.readWithContext(ScioIO.scala:74)
[error] 	at com.spotify.scio.io.ScioIO.readWithContext$(ScioIO.scala:70)
[error] 	at com.spotify.scio.io.TextIO.readWithContext(TextIO.scala:37)
[error] 	at com.spotify.scio.ScioContext.read(ScioContext.scala:794)
[error] 	at com.spotify.scio.ScioContext.textFile(ScioContext.scala:767)
[error] 	at core.Main$.main(Main.scala:13)
[error] 	at core.Main.main(Main.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] Caused by: java.lang.reflect.InvocationTargetException
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] 	at org.apache.beam.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:214)
[error] 	at org.apache.beam.sdk.util.InstanceBuilder.build(InstanceBuilder.java:155)
[error] 	at org.apache.beam.sdk.PipelineRunner.fromOptions(PipelineRunner.java:55)
[error] 	at org.apache.beam.sdk.Pipeline.create(Pipeline.java:149)
[error] 	at com.spotify.scio.ScioContext.pipeline(ScioContext.scala:498)
[error] 	at com.spotify.scio.ScioContext.applyInternal(ScioContext.scala:675)
[error] 	at com.spotify.scio.ScioContext.applyInternal(ScioContext.scala:680)
[error] 	at com.spotify.scio.io.TextIO.read(TextIO.scala:48)
[error] 	at com.spotify.scio.io.TextIO.read(TextIO.scala:37)
[error] 	at com.spotify.scio.io.ScioIO$$anonfun$readWithContext$1.apply(ScioIO.scala:77)
[error] 	at com.spotify.scio.io.ScioIO$$anonfun$readWithContext$1.apply(ScioIO.scala:74)
[error] 	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:657)
[error] 	at com.spotify.scio.io.ScioIO.readWithContext(ScioIO.scala:74)
[error] 	at com.spotify.scio.io.ScioIO.readWithContext$(ScioIO.scala:70)
[error] 	at com.spotify.scio.io.TextIO.readWithContext(TextIO.scala:37)
[error] 	at com.spotify.scio.ScioContext.read(ScioContext.scala:794)
[error] 	at com.spotify.scio.ScioContext.textFile(ScioContext.scala:767)
[error] 	at core.Main$.main(Main.scala:13)
[error] 	at core.Main.main(Main.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] Caused by: java.lang.NoSuchMethodError: 'com.google.common.cache.CacheBuilder com.google.common.cache.CacheBuilder.expireAfterWrite(java.time.Duration)'
[error] 	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.<init>(GoogleCloudStorageImpl.java:149)
[error] 	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil.<init>(GcsUtil.java:243)
[error] 	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil.<init>(GcsUtil.java:82)
[error] 	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil$GcsUtilFactory.create(GcsUtil.java:104)
[error] 	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil$GcsUtilFactory.create(GcsUtil.java:87)
[error] 	at org.apache.beam.sdk.options.ProxyInvocationHandler.returnDefaultHelper(ProxyInvocationHandler.java:592)
[error] 	at org.apache.beam.sdk.options.ProxyInvocationHandler.getDefault(ProxyInvocationHandler.java:533)
[error] 	at org.apache.beam.sdk.options.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:158)
[error] 	at com.sun.proxy.$Proxy210.getGcsUtil(Unknown Source)
[error] 	at org.apache.beam.sdk.extensions.gcp.options.GcpOptions$GcpTempLocationFactory.tryCreateDefaultBucket(GcpOptions.java:354)
[error] 	at org.apache.beam.sdk.extensions.gcp.options.GcpOptions$GcpTempLocationFactory.create(GcpOptions.java:300)
[error] 	at org.apache.beam.sdk.extensions.gcp.options.GcpOptions$GcpTempLocationFactory.create(GcpOptions.java:288)
[error] 	at org.apache.beam.sdk.options.ProxyInvocationHandler.returnDefaultHelper(ProxyInvocationHandler.java:592)
[error] 	at org.apache.beam.sdk.options.ProxyInvocationHandler.getDefault(ProxyInvocationHandler.java:533)
[error] 	at org.apache.beam.sdk.options.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:158)
[error] 	at com.sun.proxy.$Proxy202.getGcpTempLocation(Unknown Source)
[error] 	at org.apache.beam.runners.dataflow.DataflowRunner.fromOptions(DataflowRunner.java:249)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] 	at org.apache.beam.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:214)
[error] 	at org.apache.beam.sdk.util.InstanceBuilder.build(InstanceBuilder.java:155)
[error] 	at org.apache.beam.sdk.PipelineRunner.fromOptions(PipelineRunner.java:55)
[error] 	at org.apache.beam.sdk.Pipeline.create(Pipeline.java:149)
[error] 	at com.spotify.scio.ScioContext.pipeline(ScioContext.scala:498)
[error] 	at com.spotify.scio.ScioContext.applyInternal(ScioContext.scala:675)
[error] 	at com.spotify.scio.ScioContext.applyInternal(ScioContext.scala:680)
[error] 	at com.spotify.scio.io.TextIO.read(TextIO.scala:48)
[error] 	at com.spotify.scio.io.TextIO.read(TextIO.scala:37)
[error] 	at com.spotify.scio.io.ScioIO$$anonfun$readWithContext$1.apply(ScioIO.scala:77)
[error] 	at com.spotify.scio.io.ScioIO$$anonfun$readWithContext$1.apply(ScioIO.scala:74)
[error] 	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:657)
[error] 	at com.spotify.scio.io.ScioIO.readWithContext(ScioIO.scala:74)
[error] 	at com.spotify.scio.io.ScioIO.readWithContext$(ScioIO.scala:70)
[error] 	at com.spotify.scio.io.TextIO.readWithContext(TextIO.scala:37)
[error] 	at com.spotify.scio.ScioContext.read(ScioContext.scala:794)
[error] 	at com.spotify.scio.ScioContext.textFile(ScioContext.scala:767)
[error] 	at core.Main$.main(Main.scala:13)
[error] 	at core.Main.main(Main.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 6 s, completed May 5, 2020, 11:38:58 AM
```

The content of build.sbt is

```scala
name := "scio-0.9.0-error"

scalaVersion := "2.12.11"

libraryDependencies ++= Seq(
  "com.spotify" %% "scio-core" % "0.9.0",
  "org.apache.beam" % "beam-runners-google-cloud-dataflow-java" % "2.20.0",
  "org.slf4j" % "slf4j-simple" % "1.7.25"
)
```

And Main.scala

```scala
package core

import com.spotify.scio._

object Main {
  def main(args: Array[String]): Unit = {
    val (sc, _) = ContextAndArgs(Array(
      s"--project=${args(0)}",
      "--region=us-central1",
      "--runner=DataflowRunner"
    ))

    sc.textFile(args(1)).saveAsTextFile(args(2))
    sc.run()
  }
}
```

I'm submitting the job using sbt 1.3.10 with the `run` command. The same code can be submitted without error when using scio-core 0.8.4 with beam-runners-google-cloud-dataflow-java 2.19.0.

**Comment by pishen** [comment]
I've tried 0.9.1-SNAPSHOT but the result is same.

**Comment by regadas** [comment]
Hi @pishen in your case i some `beam` transitive dependencies bring `28.1-android` to the mix...

you will need to:

```scala
ThisBuild / dependencyOverrides ++= Seq(
  "com.google.guava" % "guava" % "27.0.1-jre"
)
```
