### ISSUE TITLE
Dependency conflict after upgrading to 0.5.6

### ISSUE THREAD

**Issue by Tomczik76** [spotify/scio#1267]
After upgrading Scio from 0.5.5 to 0.5.6 I'm getting this error

```
java.lang.NoSuchMethodError: com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient$Builder.setBatchPath(Ljava/lang/String;)Lcom/google/api/client/googleapis/services/AbstractGoogleClient$Builder;
        at com.google.api.services.bigquery.Bigquery$Builder.setBatchPath(Bigquery.java:3473)
        at com.google.api.services.bigquery.Bigquery$Builder.<init>(Bigquery.java:3452)
        at com.spotify.scio.bigquery.BigQueryClient.com$spotify$scio$bigquery$BigQueryClient$$bigquery$lzycompute(BigQueryClient.scala:129)
        at com.spotify.scio.bigquery.BigQueryClient.com$spotify$scio$bigquery$BigQueryClient$$bigquery(BigQueryClient.scala:119)
        at com.spotify.scio.bigquery.BigQueryClient$$anonfun$com$spotify$scio$bigquery$BigQueryClient$$run$1$1.apply(BigQueryClient.scala:566)
        at com.spotify.scio.bigquery.BigQueryClient$$anonfun$com$spotify$scio$bigquery$BigQueryClient$$run$1$1.apply(BigQueryClient.scala:551)
        at scala.util.Try$.apply(Try.scala:192)
        at com.spotify.scio.bigquery.BigQueryClient.com$spotify$scio$bigquery$BigQueryClient$$run$1(BigQueryClient.scala:551)
        at com.spotify.scio.bigquery.BigQueryClient$$anonfun$com$spotify$scio$bigquery$BigQueryClient$$runQuery$1.apply(BigQueryClient.scala:570)
        at com.spotify.scio.bigquery.BigQueryClient$$anonfun$com$spotify$scio$bigquery$BigQueryClient$$runQuery$1.apply(BigQueryClient.scala:570)
        at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:79)
        at com.spotify.scio.bigquery.BigQueryClient.com$spotify$scio$bigquery$BigQueryClient$$runQuery(BigQueryClient.scala:570)
        at com.spotify.scio.bigquery.BigQueryClient.dryRunQuery$1(BigQueryClient.scala:581)
        at com.spotify.scio.bigquery.BigQueryClient.isLegacySql(BigQueryClient.scala:589)
        at com.spotify.scio.bigquery.BigQueryClient.extractTables(BigQueryClient.scala:614)
        at com.spotify.scio.bigquery.BigQueryClient.newCachedQueryJob(BigQueryClient.scala:458)
        at com.spotify.scio.bigquery.BigQueryClient.newQueryJob(BigQueryClient.scala:448)
        at com.spotify.scio.bigquery.BigQueryClient.getQueryRows(BigQueryClient.scala:209)
```

Is that what this commit is trying to remedy?

https://github.com/spotify/scio/compare/c30712cc286c...50852920fcb6
Or
https://github.com/spotify/scio/compare/859c88910558...c30712cc286c

**Comment by nevillelyh** [comment]
Not sure if related. What's the `google-api-services-bigquery` version you have?

**Comment by nevillelyh** [comment]
I have these 2 which should be compatible with each other.
`com.google.apis:google-api-services-bigquery:v2-rev374-1.23.0`
`com.google.api-client:google-api-client:1.23.0`

**Comment by Tomczik76** [comment]
I found my issue, we had pinned this version ```com.google.api-client:1.22.0```
